version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    networks:
      - web-dev

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - web-dev

  php:
    build:
      dockerfile: ./php.Dockerfile
      context: .
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html
    image: php:8.0-apache
    ports:
      - 80:80
    networks:
      - web-dev

networks:
  web-dev:
    driver: bridge

volumes:
  db_data: {}
